#!/bin/sh
# shellcheck disable=SC2139
if command -v bat >/dev/null 2>&1; then
  alias rcat="$(which cat)"

  alias cat="$(which bat)"
fi

alias ssh="kitten ssh"
alias lf="lfcd"

# Create alias override commands using 'lsd'
alias ls='lsd --group-directories-first'
alias ll='lsd -l --group-directories-first'
alias la='lsd -la --group-directories-first'
alias lt='lsd -l --group-directories-first --tree --depth=2'
