#!/bin/sh

alias mamba="micromamba"
alias ssh="kitten ssh"
alias lf="lfcd"
alias cat="bat"

# Create alias override commands using 'lsd'
alias ls='lsd --group-directories-first'
alias ll='lsd -l --group-directories-first'
alias la='lsd -la --group-directories-first'
alias lt='lsd -l --group-directories-first --tree --depth=2'
